### ISSUE TITLE
Header information / offset list

### ISSUE THREAD

**Issue by DreamPlusInfinity** [Fluvian/lzkn64#1]
Thank you so much for working on this, especially since it could help making so many translations possible.
Do you have for all Goemon N64 games a log of all offsets with the compressed graphical data, or the text data proper?

**Comment by Fluvian** [comment]
Hello, sorry for the late reply.

I only have a log for the NTSC-J version of the first Goemon game, but nonetheless, [here ](https://gist.github.com/Fluvian/d3e63ef7ee63fdc4cf9cb17f385893d1) it is.
I annotated this a while ago, but PIC is textures and Dialog Data is all of the text data in the game.

The font is uncompressed in ROM.
