### ISSUE TITLE
Little bug

### ISSUE THREAD

**Issue by Z3R0XZ** [Fluvian/lzkn64#2]
If rleBytesLeft are equial to 0x22 the while loop will add another rle command equal the first.
https://github.com/Fluvian/lzkn64/blob/7dbcbae68f30d04be04be6d3ddfc43277660b256/lzkn64.c#L213

**Comment by Z3R0XZ** [comment]
Little hack is just check if is 0x22 and put 2 RLE commands with 0x11 size.

**Comment by Fluvian** [comment]
Could you attach the data you tried to compress with it that produced that output? What it's supposed to be doing is output multiple RLE commands for RLE sequences larger than 0x21.

**Comment by Z3R0XZ** [comment]
I'm compressing another Konami Hybrid Heaven that use the same compression, table offsets and 2 different decompression routines and both use the table to calculate actual file sizes and is a mess when you compress multiple consecutive files, I just modify the ROM deco routine to use the real file size.
This is the file I use and the bug happens at offset: 0x834A8 there are 0x22 bytes with byte 0x23
[004E69A8 Main.zip](https://github.com/Fluvian/lzkn64/files/9277461/004E69A8.Main.zip)

**Comment by Fluvian** [comment]
Commit 8478701134ead6872f98952ef63ed4a9847119da should fix this, let me know if you find anything else.
