### ISSUE TITLE
Castlevania 64 - Output files appear to be slightly wrong

### ISSUE THREAD

**Issue by Bsquo** [Fluvian/lzkn64#3]
Hi! First of all, I want to say thank you so much for making the tool! I'm glad to see a tool available for compressing/decompressing individual files for the Nisitenma-Ichigo titles! I've been testing the tool with Castlevania 64, both decompressing as well as compressing back files from the ROM. However, in both cases, the output files from LZKN64 seem to be slightly wrong.

There is a tool intended for Mystical Ninja Starring Goemon, called [Mystical Ninja Decompressor Plus](https://www.romhacking.net/utilities/1523/) that can also decompress files from Castlevania 64. The output files from this tool appear to be decompressed properly, as the texture data and display lists are formatted properly. This tool, however, doesn't have a feature to compress files back.

For example, consider this file. In a Castlevania 64 USA v1.0 ROM (`sha1: 989A28782ED6B0BC489A1BBBD7BEC355D8F2707E`), this file starts at offset 0x7A38EC and has a size of 0x1510 bytes. I have tried decompressing this file, and then recompressing it back, but the recompressed file doesn't match the original file from the ROM (plus it's slightly smaller).

In addition, the decompressed file generated by LZKN64 doesn't match the decompressed file output by Mystical Ninja Decompressor Plus. They look similar, but don't match. In the image below I compared the file decompressed by LZKN64 vs the one from Mystical Ninja Decompressor Plus using Texture64:

![123123](https://user-images.githubusercontent.com/88517417/204156543-12a97b74-c44c-4c86-a686-9ec48598cbc0.png)

In addition, it appears that some display list commands are missing in the file output by LZKN64, so I'm unable to preview the models using that file, whereas I can preview the models properly using the file output by Mystical Ninja Decompressor Plus.

[Here's the file I used on this example](https://drive.google.com/file/d/1l_87pttodPy6TwfBhSJejvyy7fEUPrLS/view?usp=sharing), I included 4 files:

* `original_file.bin`: the original compressed file extracted from the ROM.
* `MNDP_decomp.bin`: the `original_file.bin` file decompressed using Mystical Ninja Decompressor Plus.
* `LZKN64_decomp.bin`: the `original_file.bin` file decompressed using LZKN64.
* `LZKN64_recomp.bin`: `LZKN64_decomp.bin` compressed back using LZKN64. Compressing the `MNDP_decomp.bin` file using LZKN64 creates a file that matches this one, even though `MNDP_decomp.bin` and `LZKN64_decomp.bin` are not byte-identical.

Thanks again for the tool, and let me know if you need more information!

**Comment by Fluvian** [comment]
Hi, sorry for the delay in answering, GitHub doesn't notify me very well about issues, I'll take a look!

**Comment by Fluvian** [comment]
Weird, I'm not able to reproduce the error when decompressing from the original file using this tool, it seems to be correct.

The only mistake I found was that decompressing a file compressed with LZKN64 would sometimes have more bytes than the original file.

So, decompressing `original_file.bin` I get the same output as `MNDP_decomp.bin` on my machine.
Compressing that decompressed file and decompressing it *again*, I get the same file as the original input file.

The issue you mentioned with the compressed file not matching is due to me not being able to replicate their compression algorithm fully, I've been trying that for some to no avail.

What compiler are you using and what's your version?

**Comment by Bsquo** [comment]
Hi, and thanks for replying!

You're right, it turns out the issue was indeed the `gcc` version I was using to compile the program.
The terminal I've used to compile this tool at first had `gcc (MinGW.org GCC-6.3.0-1) 6.3.0`. I've tried again using WSL, which had `gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0`, and that worked perfectly, with the decompressed files now having the correct output.
I can also confirm that compressing back works great as well. I've tested recompressing some files from the ROM after being decompressed with this tool, and then injecting them in the ROM again and testing them in-game, and they worked just fine.

Regarding the compressed file not matching, it's OK. I was pointing that out as an observation, rather than as an issue, my bad! As long as the recompressed file works in-game, that's all that matters!
Sorry for the inconvenience, I didn't even think to check if my version of `gcc` was old, my apologies... Either way, modding Castlevania 64 should become easier now that we can decompress/compress back individual files!



This is unrelated, but I was wondering if you're still reversing Mystical Ninja Starring Goemon. I have found some interesting debugging functions in Castlevania 64, and most of them appear to be in MNSG, most likely due to both reusing the same engine.
One thing that I found is what appears to be leftover code for a [process meter](https://tcrf.net/images/6/68/CV64_Prerelease1.png), and some of those functions appear to be identical in MNSG as well.

**Comment by Fluvian** [comment]
> Hi, and thanks for replying!
> 
> You're right, it turns out the issue was indeed the `gcc` version I was using to compile the program. The terminal I've used to compile this tool at first had `gcc (MinGW.org GCC-6.3.0-1) 6.3.0`. I've tried again using WSL, which had `gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0`, and that worked perfectly, with the decompressed files now having the correct output. I can also confirm that compressing back works great as well. I've tested recompressing some files from the ROM after being decompressed with this tool, and then injecting them in the ROM again and testing them in-game, and they worked just fine.
> 
> Regarding the compressed file not matching, it's OK. I was pointing that out as an observation, rather than as an issue, my bad! As long as the recompressed file works in-game, that's all that matters! Sorry for the inconvenience, I didn't even think to check if my version of `gcc` was old, my apologies... Either way, modding Castlevania 64 should become easier now that we can decompress/compress back individual files!
> 
> This is unrelated, but I was wondering if you're still reversing Mystical Ninja Starring Goemon. I have found some interesting debugging functions in Castlevania 64, and most of them appear to be in MNSG, most likely due to both reusing the same engine. One thing that I found is what appears to be leftover code for a [process meter](https://tcrf.net/images/6/68/CV64_Prerelease1.png), and some of those functions appear to be identical in MNSG as well.

Glad you were able to get it working! That's fine, I don't mind helping at all.

Ooh, that sounds interesting, yes I'm still reversing MNSG along with Goemon's Great Adventure, that process meter code would be really interesting to look at, I've been looking for debug functionality in the game! Any way we could talk on Discord?

**Comment by Bsquo** [comment]
For sure, my Discord is B_squo#5127
