### ISSUE TITLE
Worst compression ratio

### ISSUE THREAD

**Issue by Z3R0XZ** [Fluvian/lzkn64#5]
I'm testing the newest version on Hybrid Heaven, and indeed, it matches the original compression data, but when some bytes are changed on the file, the new size is bigger than the preview version or the LZKN, and the compression speed is slower.
Matching the original files is great, but modding is kind of hard without rebuilding the table file and offsets. Hybrid Heaven even uses the next file in the table to calculate the curret file size; I don't know if other Konami games do that, which is a pain, and I have to modify the mips routine to use the file header or the first 4 bytes of the compressed file that has the file size.

Using the same file with a size of 0x89CF0, I get this.

The old version compressed the file to 0x54960 bytes, and the new version compressed the file to 0x55E10 bytes, the original compressed size was 0x55DD4 bytes.

**Comment by Fluvian** [comment]
The goal of this program was to match the original compression so one could get a decomp project matching, but if there's a need I could add a mode for a better compression ratio which then doesn't match the original.

**Comment by Z3R0XZ** [comment]
Yeah, that should tackle both scenarios. Asking the user what type of compression or ratio they need should do it.

**Comment by Fluvian** [comment]
This has been fixed as of commit fc45f58, use the program with the `-e` option to use a more efficient compression algorithm.
